import React from 'react'
import { Col, Container, Row } from 'react-bootstrap'

const WhyUs = () => {
  return (
    <div className='whyUS'>
        <Container>
            <Row>
                <Col>
                    <h1 className='text-center py-4'>WHY CHOSE US</h1>

                    <h5 className='textJustify mb-4'>1 Cost Effective – We are very well known that how much you have worked hard for your savings. In addition, we want you to save as much as possible on your trips and get the best services and other VIP facilities within that budget at the same time. This is where our cheap tour packages from Bangladesh come into play. Our tour packages are designed in such a manner that you are bound to get the best facilities and services within a very low budget. You will not get such pleasure in such a little amount of money in any other agencies. We believe in quality more than anything. Thus ensuring that your vacation goes as planned and your satisfaction level reaches to a new height. This is how we achieve our clients’ trust. The clients that we have already served have now made us their permanent traveling partner and they are happy with our cheap tour packages and overall services. We even provide discounts to our loyal customers. So give us a try today and let us have the honor of becoming a part of your life by fulfilling your traveling satisfaction in the cheapest way possible.</h5>

                    <h5 className='textJustify mb-4'>2 No hidden charges– This is the most common thing that is suffered by most of the people. Even we face many questions regarding hidden charges. Therefore, Oboskash travel agency has a policy that says “NO HIDDEN CHARGES”. We like our information and packages to be transparent for our clients. In these cases, we are just like as an open book. When we put a price on our cheap tour packages, we mean that amount only! We will provide you the costing in details of that particular package which you wish to enjoy. We do not want to disappoint our customers and we are not one of those agencies who play hide and seeks with the costs. So, therefore, we are transparent when it comes to the pricing and costing of tour packages. The clients we served trust us because of our transparency towards the cost and the fact that we keep our commitments and thus refer us to other clients. </h5>

                    <h5 className='textJustify mb-4'>3 Quality Assurance– This is the next important thing after costing factor. If you take one or two weeks off from your everyday life, you want these weeks to be the most relaxing and fun-filled weeks of your life. We know how hard it is to take days off from work. Many companies do not approve such a long vacation. However, once it does, each second of those days' counts and matters to you. Therefore, Obokash travel agency is here to make sure that you get nothing but relaxation and fun throughout your entire holiday, making a memorable holiday for you. We promise that at the end of your tour you will definitely feel pleased and mentally satisfied to its core. You will not feel like ending your tour. Our quality of service will definitely make you feel like you are at home and enjoying the natures mesmerizing view, and the exoticness of nature will refresh you and energize you fully making you ready to get back to your regular life until next time you need us to energize you again. We will provide you the best accommodations, food, and flights possible within a very low budget that will give you the best pleasure and satisfaction, keeping the service top-notch and budget friendly as well. Our services will create a new comfort zone for you, which you will love and enjoy the most. We guarantee that you will enjoy and have fun with our loved ones during your holidays. So do not wait anymore, book your package with us today, and have an experience of a lifetime. </h5>

                    <h5 className='textJustify mb-4'>4 Hassle-free traveling– What is the point of traveling if you have to through a lot of hassles and obstacles? To ensure that this trust and mood-breaking experience do not happen, our expert team is there to take care of it all. Right after you choose your tour package, the first thing that can be a problem is with the visa. As mentioned earlier, we were the best visa-processing agency in Bangladesh, it will not be a challenge for us. We will need a few documents from you and the rest is our headache. Once we receive your visa, rests on the procedures are very easy. We will book and buy the ticket of the airlines in which you will be traveling to your destination. We will give you the best airlines, which have the best quality of service. For your accommodations, we will book the best hotel there is available and most importantly, a hotel, which is well secured. Security of our customers is one of the major priorities that we give. You cannot have fun and enjoy if you have the tension of your belongings in the back end of your mind. We have experienced and expert guides for you to guide you everywhere and give you the tour of different famous and relaxing places with views that will mesmerize you. The expert guide will ensure that you face no problems and stay completely hassle free throughout the entire tour, just relax, and have fun.</h5>
                </Col>
            </Row>
        </Container>
    </div>
  )
}

export default WhyUs